-- Оплата через Робокассу: заказ, зачисление по уведомлению Result, сверка.
--
-- До этой миграции баланс пополнял только владелец вручную
-- (admin_record_verified_top_up, source = 'admin'). Вариант source =
-- 'provider' был заложен тогда же, и зачисление от провайдера пишет в ту же
-- private.verified_balance_top_ups: выручка дашборда, сверка и лента
-- платежей админки подхватывают его без правок.
--
-- Правила, которые держит база, а не сервер:
--   * Заказ заводит только service_role: сумму из браузера не назначить,
--     номер InvId выдаёт последовательность.
--   * Деньги зачисляет только confirm_payment_order и только если сумма и
--     режим (тест/бой) совпали с заказом. Повторное уведомление Result
--     ничего не меняет: заказ заперт на время подтверждения, а ссылка
--     провайдера у пополнения уникальна.
--   * Тестовый заказ - только у служебного аккаунта (private.is_staff).
--     База у превью и прода одна, и тестовый режим Робокассы не должен
--     давать деньги ученикам.
--   * Пределы суммы - зеркало src/lib/topUpLimits.ts.

-- ---------------------------------------------------------------------------
-- Заказы
-- ---------------------------------------------------------------------------

-- Номера с 100001: тестовые и боевые заказы идут из одной
-- последовательности, поэтому номер не повторяется между режимами.
create table if not exists private.payment_orders (
  inv_id integer generated by default as identity (start with 100001) primary key,
  -- Аккаунт могут удалить, пока идёт оплата. Заказ при этом остаётся:
  -- по нему делается возврат.
  user_id uuid references auth.users(id) on delete set null,
  amount integer not null check (amount > 0),
  is_test boolean not null default false,
  status text not null default 'pending' check (status in ('pending', 'paid', 'cancelled', 'expired')),
  top_up_id uuid references private.verified_balance_top_ups(id) on delete set null,
  paid_via text check (paid_via in ('result', 'reconcile', 'status')),
  provider_payload jsonb not null default '{}'::jsonb,
  check_attempts integer not null default 0,
  next_check_at timestamptz not null default now() + interval '2 minutes',
  last_checked_at timestamptz,
  created_at timestamptz not null default now(),
  paid_at timestamptz,
  closed_at timestamptz,
  constraint payment_orders_paid_state check ((status = 'paid') = (paid_at is not null))
);

create index if not exists payment_orders_user_created_idx on private.payment_orders (user_id, created_at desc);
create index if not exists payment_orders_pending_check_idx on private.payment_orders (next_check_at) where status = 'pending';

alter table private.payment_orders enable row level security;
revoke all on table private.payment_orders from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Зачисление от провайдера.
--
-- Та же логика, что у admin_record_verified_top_up, без проверки роли
-- администратора и без записи в журнал админки: действие совершил не
-- администратор, а платёж. Ручной путь не тронут.
-- ---------------------------------------------------------------------------

create or replace function private.credit_provider_top_up(
  p_user_id uuid,
  p_amount integer,
  p_reference text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  normalized_reference text := lower(trim(coalesce(p_reference, '')));
  existing_top_up private.verified_balance_top_ups%rowtype;
  referral public.referral_invites%rowtype;
  top_up_id uuid := gen_random_uuid();
  top_up_entry_id uuid;
  referrer_entry_id uuid;
  invitee_entry_id uuid;
  current_balance integer;
  new_balance integer;
  referrer_balance integer;
  first_top_up boolean;
  referral_rewarded boolean := false;
begin
  if p_amount is null or p_amount not between 1 and 100000000 then
    raise exception 'top up amount must be between 1 and 1000000' using errcode = '22023';
  end if;

  if char_length(normalized_reference) not between 6 and 160
    or normalized_reference !~ '^[a-z0-9][a-z0-9._:/-]*$' then
    raise exception 'invalid provider reference' using errcode = '22023';
  end if;

  select * into existing_top_up
  from private.verified_balance_top_ups
  where provider_reference = normalized_reference;

  if found then
    if existing_top_up.user_id <> p_user_id or existing_top_up.amount <> p_amount then
      raise exception 'provider reference conflict' using errcode = '23505';
    end if;
    return jsonb_build_object('applied', false, 'topUpId', existing_top_up.id, 'amount', existing_top_up.amount);
  end if;

  select balance into current_balance
  from public.wallet_accounts
  where user_id = p_user_id
  for update;

  if current_balance is null then
    raise exception 'wallet not found' using errcode = 'P0002';
  end if;

  first_top_up := not exists (
    select 1 from private.verified_balance_top_ups
    where user_id = p_user_id
  );

  update public.wallet_accounts
  set balance = current_balance + p_amount,
      updated_at = now()
  where user_id = p_user_id
  returning balance into new_balance;

  insert into public.wallet_entries (user_id, amount, kind, description, idempotency_key)
  values (p_user_id, p_amount, 'credit', 'Пополнение баланса', 'verified-top-up:' || md5(normalized_reference))
  returning id into top_up_entry_id;

  insert into private.verified_balance_top_ups (id, user_id, actor_id, provider_reference, amount, wallet_entry_id, source)
  values (top_up_id, p_user_id, null, normalized_reference, p_amount, top_up_entry_id, 'provider');

  -- Награда за приглашение обычно уже выдана при подтверждении почты
  -- (20260831090000). Здесь она находит только приглашение, которое всё ещё
  -- ждёт, - как и ручной путь, - и второй раз заплатить не может.
  if first_top_up then
    select * into referral
    from public.referral_invites
    where invitee_user_id = p_user_id
      and status = 'pending'
    for update;

    if found then
      select balance into referrer_balance
      from public.wallet_accounts
      where user_id = referral.referrer_user_id
      for update;

      if referrer_balance is null then
        raise exception 'referrer wallet not found' using errcode = 'P0002';
      end if;

      update public.wallet_accounts
      set balance = balance + referral.referrer_reward_amount,
          updated_at = now()
      where user_id = referral.referrer_user_id;

      insert into public.wallet_entries (user_id, amount, kind, description, idempotency_key)
      values (referral.referrer_user_id, referral.referrer_reward_amount, 'credit', 'Бонус за приглашённого друга', 'referral-referrer:' || referral.id::text)
      returning id into referrer_entry_id;

      update public.wallet_accounts
      set balance = balance + referral.invitee_reward_amount,
          updated_at = now()
      where user_id = referral.invitee_user_id
      returning balance into new_balance;

      insert into public.wallet_entries (user_id, amount, kind, description, idempotency_key)
      values (referral.invitee_user_id, referral.invitee_reward_amount, 'credit', 'Бонус за регистрацию по приглашению', 'referral-invitee:' || referral.id::text)
      returning id into invitee_entry_id;

      update public.referral_invites
      set status = 'rewarded',
          qualifying_top_up_id = top_up_id,
          referrer_wallet_entry_id = referrer_entry_id,
          invitee_wallet_entry_id = invitee_entry_id,
          rewarded_at = now()
      where id = referral.id;

      referral_rewarded := true;
    end if;
  end if;

  return jsonb_build_object(
    'applied', true,
    'topUpId', top_up_id,
    'amount', p_amount,
    'balance', new_balance,
    'referralRewarded', referral_rewarded
  );
end;
$function$;

revoke all on function private.credit_provider_top_up(uuid, integer, text) from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Новый заказ. Зовёт сервер после проверки сессии ученика.
-- ---------------------------------------------------------------------------

create or replace function public.create_payment_order(p_user_id uuid, p_amount integer, p_is_test boolean)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  recent_orders integer;
  new_inv_id integer;
  test_order boolean := coalesce(p_is_test, false);
begin
  -- Зеркало src/lib/topUpLimits.ts: от 50 до 15 000 ₽, целыми рублями.
  if p_amount is null or p_amount < 5000 or p_amount > 1500000 or p_amount % 100 <> 0 then
    raise exception 'top up amount out of range' using errcode = '22023';
  end if;

  if p_user_id is null or not exists (select 1 from public.profiles where id = p_user_id) then
    raise exception 'user not found' using errcode = 'P0002';
  end if;

  if exists (select 1 from public.account_controls where user_id = p_user_id and is_banned) then
    raise exception 'account is blocked' using errcode = '42501';
  end if;

  if test_order and not private.is_staff(p_user_id) then
    raise exception 'test payments are staff only' using errcode = '42501';
  end if;

  -- Незакрытый заказ ничего не стоит, но двадцать в час - уже не человек.
  select count(*) into recent_orders
  from private.payment_orders
  where user_id = p_user_id
    and created_at > now() - interval '1 hour';

  if recent_orders >= 20 then
    raise exception 'too many payment orders' using errcode = '54000';
  end if;

  insert into private.payment_orders (user_id, amount, is_test)
  values (p_user_id, p_amount, test_order)
  returning inv_id into new_inv_id;

  return jsonb_build_object('invId', new_inv_id, 'amount', p_amount, 'isTest', test_order);
end;
$function$;

-- ---------------------------------------------------------------------------
-- Подтверждение оплаты: уведомление Result, сверка по крону или проверка
-- по возвращении ученика. Подпись проверяет сервер, сумму и режим - база.
-- ---------------------------------------------------------------------------

create or replace function public.confirm_payment_order(
  p_inv_id integer,
  p_amount integer,
  p_is_test boolean,
  p_via text,
  p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  payment private.payment_orders%rowtype;
  credit jsonb;
begin
  if p_via is null or p_via not in ('result', 'reconcile', 'status') then
    raise exception 'invalid payment source' using errcode = '22023';
  end if;

  select * into payment
  from private.payment_orders
  where inv_id = p_inv_id
  for update;

  if not found then
    raise exception 'payment order not found' using errcode = 'P0002';
  end if;

  if payment.is_test <> coalesce(p_is_test, false) then
    raise exception 'payment mode mismatch' using errcode = '22023';
  end if;

  if payment.amount <> p_amount then
    raise exception 'payment amount mismatch' using errcode = '22023';
  end if;

  if payment.status = 'paid' then
    return jsonb_build_object('applied', false, 'status', 'paid', 'invId', payment.inv_id);
  end if;

  -- Отменённый или просроченный заказ тоже принимается: подпись верна,
  -- значит, деньги пришли, а своё «отменён» мы могли поставить раньше,
  -- чем Робокасса провела платёж.
  -- Аккаунт удалён, пока ученик платил: зачислять некуда. Заказ всё
  -- равно отмечается оплаченным, дальше - возврат вручную.
  if payment.user_id is not null then
    credit := private.credit_provider_top_up(
      payment.user_id,
      payment.amount,
      case when payment.is_test then 'robokassa-test:' else 'robokassa:' end || payment.inv_id::text
    );
  end if;

  update private.payment_orders
  set status = 'paid',
      paid_at = now(),
      closed_at = now(),
      paid_via = p_via,
      top_up_id = (credit ->> 'topUpId')::uuid,
      provider_payload = coalesce(p_payload, '{}'::jsonb)
  where inv_id = payment.inv_id;

  return jsonb_build_object(
    'applied', coalesce((credit ->> 'applied')::boolean, false),
    'status', 'paid',
    'invId', payment.inv_id,
    'unassigned', payment.user_id is null
  );
end;
$function$;

-- ---------------------------------------------------------------------------
-- Статус своего заказа - для экрана возврата из Робокассы.
-- ---------------------------------------------------------------------------

create or replace function public.payment_order_status(p_user_id uuid, p_inv_id integer)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $function$
  select jsonb_build_object(
    'invId', inv_id,
    'amount', amount,
    'status', status,
    'isTest', is_test,
    'createdAt', created_at,
    'paidAt', paid_at
  )
  from private.payment_orders
  where inv_id = p_inv_id
    and user_id = p_user_id;
$function$;

-- Запрос статуса у Робокассы по возвращении ученика - не чаще раза в
-- десять секунд на заказ, иначе обновление страницы превращается в
-- обстрел их API.
create or replace function public.claim_payment_order_check(p_user_id uuid, p_inv_id integer)
returns boolean
language plpgsql
security definer
set search_path = ''
as $function$
begin
  update private.payment_orders
  set last_checked_at = now()
  where inv_id = p_inv_id
    and user_id = p_user_id
    and status = 'pending'
    and created_at < now() - interval '10 seconds'
    and (last_checked_at is null or last_checked_at < now() - interval '10 seconds');
  return found;
end;
$function$;

-- ---------------------------------------------------------------------------
-- Сверка: заказы, по которым пора спросить Робокассу. Функция сразу
-- отодвигает следующую проверку, поэтому два крона один заказ не возьмут.
-- Первая проверка - через две минуты после заказа, дальше 1, 2, 4 … 60 минут.
-- ---------------------------------------------------------------------------

create or replace function public.payment_orders_due(p_limit integer default 20)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  result jsonb;
begin
  with due as (
    select inv_id
    from private.payment_orders
    where status = 'pending'
      and next_check_at <= now()
    order by next_check_at
    limit greatest(1, least(coalesce(p_limit, 20), 50))
    for update skip locked
  ), claimed as (
    update private.payment_orders o
    set check_attempts = o.check_attempts + 1,
        last_checked_at = now(),
        next_check_at = now() + least(interval '60 minutes', interval '1 minute' * power(2, least(o.check_attempts, 6)))
    from due
    where o.inv_id = due.inv_id
    returning o.inv_id, o.amount, o.is_test, o.created_at
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'invId', inv_id,
    'amount', amount,
    'isTest', is_test,
    'createdAt', created_at
  ) order by inv_id), '[]'::jsonb)
  into result
  from claimed;

  return result;
end;
$function$;

create or replace function public.close_payment_order(p_inv_id integer, p_status text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if p_status is null or p_status not in ('cancelled', 'expired') then
    raise exception 'invalid payment order status' using errcode = '22023';
  end if;

  update private.payment_orders
  set status = p_status,
      closed_at = now()
  where inv_id = p_inv_id
    and status = 'pending';
  return found;
end;
$function$;

create or replace function public.payment_user_is_staff(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $function$
  select private.is_staff(p_user_id);
$function$;

-- Всё это зовёт только сервер служебной ролью.
revoke all on function public.create_payment_order(uuid, integer, boolean) from public, anon, authenticated;
revoke all on function public.confirm_payment_order(integer, integer, boolean, text, jsonb) from public, anon, authenticated;
revoke all on function public.payment_order_status(uuid, integer) from public, anon, authenticated;
revoke all on function public.claim_payment_order_check(uuid, integer) from public, anon, authenticated;
revoke all on function public.payment_orders_due(integer) from public, anon, authenticated;
revoke all on function public.close_payment_order(integer, text) from public, anon, authenticated;
revoke all on function public.payment_user_is_staff(uuid) from public, anon, authenticated;

grant execute on function public.create_payment_order(uuid, integer, boolean) to service_role;
grant execute on function public.confirm_payment_order(integer, integer, boolean, text, jsonb) to service_role;
grant execute on function public.payment_order_status(uuid, integer) to service_role;
grant execute on function public.claim_payment_order_check(uuid, integer) to service_role;
grant execute on function public.payment_orders_due(integer) to service_role;
grant execute on function public.close_payment_order(integer, text) to service_role;
grant execute on function public.payment_user_is_staff(uuid) to service_role;
